FROM kukymbr/goose-docker:latest AS goose-bin

FROM alpine:3.20

RUN apk --no-cache add ca-certificates tzdata

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /migrations

COPY --from=goose-bin /bin/goose /usr/local/bin/goose

COPY ./db/migrations /migrations

ENTRYPOINT ["/usr/local/bin/goose", "-dir=/migrations", "up"]